# Generated by Django 5.0.9 on 2025-09-06 15:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_salesrep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='is_primary',
            field=models.BooleanField(blank=True, help_text='Primary contact for this supplier', null=True),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='total_orders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='minimum_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='is_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
