# Generated by Django 5.0.9 on 2025-09-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_add_price_list_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary contact for this supplier'),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=3, help_text='Lead time in days'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30, help_text='Payment terms in days'),
        ),
    ]
