# Generated by Django 5.0.9 on 2025-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_salesrep_is_active_alter_salesrep_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, help_text='Description of supplier and specialties'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('internal', 'Internal Farm'), ('external', 'External Supplier')], default='external', help_text='Type of supplier - internal farm or external supplier', max_length=20),
        ),
    ]
