# COMPLETE PRODUCT BACKUP - 132 Products with Unit Variations
# Generated after adding unit variations for better order processing

from django.core.management.base import BaseCommand
from django.db import transaction
from products.models import Product, Department
from decimal import Decimal

class Command(BaseCommand):
    help = "Seed products with unit variations for enhanced order processing"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Clear existing products before importing",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            self.stdout.write("Clearing existing products...")
            Product.objects.all().delete()
            self.stdout.write(self.style.SUCCESS("Existing products cleared."))

        self.create_departments()
        self.create_products()

        self.stdout.write(self.style.SUCCESS(f"\n🎉 PRODUCTS WITH UNIT VARIATIONS CREATED SUCCESSFULLY!"))
        self.stdout.write(self.style.SUCCESS(f"📊 Total products: 132"))

    def create_departments(self):
        departments_data = [
            {"name": "Fruits"},
            {"name": "Herbs & Spices"},
            {"name": "Mushrooms"},
            {"name": "Specialty Items"},
            {"name": "Vegetables"},
        ]
        for data in departments_data:
            Department.objects.get_or_create(name=data["name"])
        self.stdout.write(self.style.SUCCESS("Departments ensured."))

    def create_products(self):
        departments = {dept.name: dept for dept in Department.objects.all()}

        products_data = [
            {
                "name": "Avocados (Hard)",
                "department": "Fruits",
                "unit": "box",
                "price": 100.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Avocados (Hard)",
                "department": "Fruits",
                "unit": "kg",
                "price": 80.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Avocados (Hard) - kg unit variation",
            },
            {
                "name": "Avocados (Hard)",
                "department": "Fruits",
                "unit": "piece",
                "price": 15.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Avocados (Hard) - piece unit variation",
            },
            {
                "name": "Avocados (Semi-Ripe)",
                "department": "Fruits",
                "unit": "box",
                "price": 110.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Avocados (Soft)",
                "department": "Fruits",
                "unit": "box",
                "price": 120.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Bananas",
                "department": "Fruits",
                "unit": "kg",
                "price": 20.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Black Grapes",
                "department": "Fruits",
                "unit": "kg",
                "price": 60.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Blueberries",
                "department": "Fruits",
                "unit": "punnet",
                "price": 35.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Box Pineapple",
                "department": "Fruits",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Grapefruit",
                "department": "Fruits",
                "unit": "kg",
                "price": 28.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Green Grapes",
                "department": "Fruits",
                "unit": "punnet",
                "price": 45.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Lemon",
                "department": "Fruits",
                "unit": "kg",
                "price": 30.0,
                "stock_level": 50.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Lemon - Added for order processing",
            },
            {
                "name": "Lemons",
                "department": "Fruits",
                "unit": "bag",
                "price": 27.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Lemons - bag unit variation",
            },
            {
                "name": "Lemons",
                "department": "Fruits",
                "unit": "box",
                "price": 34.5,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Lemons - box unit variation",
            },
            {
                "name": "Lemons",
                "department": "Fruits",
                "unit": "kg",
                "price": 30.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Lemons box",
                "department": "Fruits",
                "unit": "box",
                "price": 34.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Lime",
                "department": "Fruits",
                "unit": "bag",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Naartjies",
                "department": "Fruits",
                "unit": "box",
                "price": 45.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Oranges",
                "department": "Fruits",
                "unit": "bag",
                "price": 23.75,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Oranges - bag unit variation",
            },
            {
                "name": "Oranges",
                "department": "Fruits",
                "unit": "box",
                "price": 27.5,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Oranges - box unit variation",
            },
            {
                "name": "Oranges",
                "department": "Fruits",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Papaya",
                "department": "Fruits",
                "unit": "punnet",
                "price": 30.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Paw Paw",
                "department": "Fruits",
                "unit": "punnet",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Pineapple",
                "department": "Fruits",
                "unit": "each",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Red Apples",
                "department": "Fruits",
                "unit": "kg",
                "price": 35.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Red Grapes",
                "department": "Fruits",
                "unit": "punnet",
                "price": 45.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Strawberries",
                "department": "Fruits",
                "unit": "box",
                "price": 50.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Strawberries - box unit variation",
            },
            {
                "name": "Strawberries",
                "department": "Fruits",
                "unit": "kg",
                "price": 62.5,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Strawberries - kg unit variation",
            },
            {
                "name": "Strawberries",
                "department": "Fruits",
                "unit": "punnet",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Sweet Melon",
                "department": "Fruits",
                "unit": "each",
                "price": 40.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Water Melon",
                "department": "Fruits",
                "unit": "each",
                "price": 50.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Watermelon",
                "department": "Fruits",
                "unit": "each",
                "price": 50.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Baby Spinach",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 45.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Basil",
                "department": "Herbs & Spices",
                "unit": "bunch",
                "price": 15.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Chives",
                "department": "Herbs & Spices",
                "unit": "piece",
                "price": 35.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Coriander",
                "department": "Herbs & Spices",
                "unit": "bunch",
                "price": 8.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Crushed Garlic",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 90.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Dill",
                "department": "Herbs & Spices",
                "unit": "bunch",
                "price": 15.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Garlic Cloves",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 80.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Ginger",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 150.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Green Chili",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 45.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Mint",
                "department": "Herbs & Spices",
                "unit": "bunch",
                "price": 10.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Packets Mint",
                "department": "Herbs & Spices",
                "unit": "bunch",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Packets Rosemary",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Packets Thyme",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Parsley",
                "department": "Herbs & Spices",
                "unit": "bunch",
                "price": 8.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Red Chili",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 80.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Rocket",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 120.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Rosemary",
                "department": "Herbs & Spices",
                "unit": "bunch",
                "price": 12.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Thyme",
                "department": "Herbs & Spices",
                "unit": "bunch",
                "price": 12.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Turmeric",
                "department": "Herbs & Spices",
                "unit": "kg",
                "price": 150.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Brown Mushrooms",
                "department": "Mushrooms",
                "unit": "kg",
                "price": 80.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Button Mushrooms",
                "department": "Mushrooms",
                "unit": "punnet",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Portabellini Mushrooms",
                "department": "Mushrooms",
                "unit": "kg",
                "price": 90.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Cherry Tomatoes",
                "department": "Specialty Items",
                "unit": "punnet",
                "price": 20.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Edible Flowers",
                "department": "Specialty Items",
                "unit": "packet",
                "price": 35.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Eggs (Jumbo)",
                "department": "Specialty Items",
                "unit": "box",
                "price": 75.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Jumbo eggs - 30 count box",
            },
            {
                "name": "Eggs (Large)",
                "department": "Specialty Items",
                "unit": "box",
                "price": 65.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Large eggs - 30 count box",
            },
            {
                "name": "Eggs (Medium)",
                "department": "Specialty Items",
                "unit": "box",
                "price": 55.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Medium eggs - 30 count box",
            },
            {
                "name": "Free Range Eggs",
                "department": "Specialty Items",
                "unit": "box",
                "price": 85.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Free range eggs - 30 count box",
            },
            {
                "name": "Large Veggie Box",
                "department": "Specialty Items",
                "unit": "box",
                "price": 320.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Micro Greens",
                "department": "Specialty Items",
                "unit": "kg",
                "price": 40.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Micro Herbs",
                "department": "Specialty Items",
                "unit": "packet",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Small Veggie Box",
                "department": "Specialty Items",
                "unit": "box",
                "price": 180.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "eggs",
                "department": "Specialty Items",
                "unit": "box",
                "price": 65.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Artichokes",
                "department": "Vegetables",
                "unit": "kg",
                "price": 45.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Aubergine",
                "department": "Vegetables",
                "unit": "kg",
                "price": 55.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Aubergine box",
                "department": "Vegetables",
                "unit": "box",
                "price": 120.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Baby Corn",
                "department": "Vegetables",
                "unit": "punnet",
                "price": 20.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Baby Marrow",
                "department": "Vegetables",
                "unit": "kg",
                "price": 35.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Baby Potatoes",
                "department": "Vegetables",
                "unit": "kg",
                "price": 30.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Beetroot",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Box Cucumber",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Broccoli",
                "department": "Vegetables",
                "unit": "box",
                "price": 45.5,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Broccoli - box unit variation",
            },
            {
                "name": "Broccoli",
                "department": "Vegetables",
                "unit": "head",
                "price": 35.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Broccoli",
                "department": "Vegetables",
                "unit": "kg",
                "price": 52.5,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Broccoli - kg unit variation",
            },
            {
                "name": "Brussels Sprouts",
                "department": "Vegetables",
                "unit": "kg",
                "price": 50.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Butter Nut",
                "department": "Vegetables",
                "unit": "kg",
                "price": 22.0,
                "stock_level": 50.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Butter Nut - Added for order processing",
            },
            {
                "name": "Butternut",
                "department": "Vegetables",
                "unit": "kg",
                "price": 22.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Carrots",
                "department": "Vegetables",
                "unit": "bag",
                "price": 22.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Carrots - bag unit variation",
            },
            {
                "name": "Carrots",
                "department": "Vegetables",
                "unit": "bunch",
                "price": 12.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Carrots - bunch unit variation",
            },
            {
                "name": "Carrots",
                "department": "Vegetables",
                "unit": "kg",
                "price": 20.0,
                "stock_level": 50.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Carrots - Added for order processing",
            },
            {
                "name": "Carrots (1kg Packed)",
                "department": "Vegetables",
                "unit": "kg",
                "price": 22.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Carrots (Loose)",
                "department": "Vegetables",
                "unit": "kg",
                "price": 20.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Cauliflower",
                "department": "Vegetables",
                "unit": "box",
                "price": 37.5,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Cauliflower - box unit variation",
            },
            {
                "name": "Cauliflower",
                "department": "Vegetables",
                "unit": "head",
                "price": 30.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Cauliflower",
                "department": "Vegetables",
                "unit": "kg",
                "price": 42.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Cauliflower - kg unit variation",
            },
            {
                "name": "Celery",
                "department": "Vegetables",
                "unit": "kg",
                "price": 40.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Cocktail Tomatoes",
                "department": "Vegetables",
                "unit": "punnet",
                "price": 18.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Crispy Lettuce",
                "department": "Vegetables",
                "unit": "box",
                "price": 40.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Cucumber",
                "department": "Vegetables",
                "unit": "box",
                "price": 20.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Cucumber - box unit variation",
            },
            {
                "name": "Cucumber",
                "department": "Vegetables",
                "unit": "each",
                "price": 8.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Cucumber",
                "department": "Vegetables",
                "unit": "kg",
                "price": 24.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Cucumber - kg unit variation",
            },
            {
                "name": "Cucumber Box",
                "department": "Vegetables",
                "unit": "box",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Deveined Spinach",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Eggplant",
                "department": "Vegetables",
                "unit": "kg",
                "price": 45.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Green Beans",
                "department": "Vegetables",
                "unit": "kg",
                "price": 45.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Green Cabbage",
                "department": "Vegetables",
                "unit": "head",
                "price": 20.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Green Chillies",
                "department": "Vegetables",
                "unit": "kg",
                "price": 75.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Green Peppers",
                "department": "Vegetables",
                "unit": "box",
                "price": 60.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Green Peppers - box unit variation",
            },
            {
                "name": "Green Peppers",
                "department": "Vegetables",
                "unit": "kg",
                "price": 50.0,
                "stock_level": 50.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Green Peppers",
                "department": "Vegetables",
                "unit": "piece",
                "price": 15.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Green Peppers - piece unit variation",
            },
            {
                "name": "Iceberg Lettuce",
                "department": "Vegetables",
                "unit": "head",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Lettuce Head",
                "department": "Vegetables",
                "unit": "box",
                "price": 21.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Lettuce Head - box unit variation",
            },
            {
                "name": "Lettuce Head",
                "department": "Vegetables",
                "unit": "head",
                "price": 15.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Lettuce Head",
                "department": "Vegetables",
                "unit": "kg",
                "price": 27.0,
                "stock_level": 20.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Lettuce Head - kg unit variation",
            },
            {
                "name": "Mixed Lettuce",
                "department": "Vegetables",
                "unit": "box",
                "price": 25.0,
                "stock_level": 10.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Mixed Lettuce - box unit",
            },
            {
                "name": "Mixed Lettuce",
                "department": "Vegetables",
                "unit": "kg",
                "price": 35.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Mixed Peppers",
                "department": "Vegetables",
                "unit": "kg",
                "price": 50.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Packets Dill",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Packets Rocket",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Patty Pan",
                "department": "Vegetables",
                "unit": "each",
                "price": 8.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Potatoes",
                "department": "Vegetables",
                "unit": "bag",
                "price": 45.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Potatoes",
                "department": "Vegetables",
                "unit": "box",
                "price": 54.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Potatoes - box unit variation",
            },
            {
                "name": "Potatoes",
                "department": "Vegetables",
                "unit": "kg",
                "price": 31.5,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Potatoes - kg unit variation",
            },
            {
                "name": "Punnets Strawberries",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Red Cabbage",
                "department": "Vegetables",
                "unit": "head",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Red Chillies",
                "department": "Vegetables",
                "unit": "kg",
                "price": 80.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Red Onions",
                "department": "Vegetables",
                "unit": "bag",
                "price": 35.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Red Peppers",
                "department": "Vegetables",
                "unit": "box",
                "price": 66.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Red Peppers - box unit variation",
            },
            {
                "name": "Red Peppers",
                "department": "Vegetables",
                "unit": "kg",
                "price": 55.0,
                "stock_level": 50.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Red Peppers",
                "department": "Vegetables",
                "unit": "piece",
                "price": 22.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Red Peppers - piece unit variation",
            },
            {
                "name": "Spring Onions",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Sweet Corn",
                "department": "Vegetables",
                "unit": "punnet",
                "price": 15.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Sweet Potatoes",
                "department": "Vegetables",
                "unit": "kg",
                "price": 28.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Tomatoes",
                "department": "Vegetables",
                "unit": "box",
                "price": 30.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Tomatoes - box unit variation",
            },
            {
                "name": "Tomatoes",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Tomatoes",
                "department": "Vegetables",
                "unit": "punnet",
                "price": 20.0,
                "stock_level": 25.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Tomatoes - punnet unit variation",
            },
            {
                "name": "White Onions",
                "department": "Vegetables",
                "unit": "bag",
                "price": 30.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Whole Tomatoes",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 50.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "Whole Tomatoes - Added for order processing",
            },
            {
                "name": "Wild Rocket",
                "department": "Vegetables",
                "unit": "kg",
                "price": 25.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
            {
                "name": "Yellow Peppers",
                "department": "Vegetables",
                "unit": "kg",
                "price": 60.0,
                "stock_level": 0.0,
                "minimum_stock": 5.0,
                "is_active": True,
                "description": "",
            },
        ]

        for data in products_data:
            Product.objects.get_or_create(
                name=data["name"],
                department=departments[data["department"]],
                unit=data["unit"],
                defaults={
                    "price": Decimal(str(data["price"])),
                    "stock_level": Decimal(str(data["stock_level"])),
                    "minimum_stock": Decimal(str(data["minimum_stock"])),
                    "is_active": data["is_active"],
                    "description": data["description"],
                }
            )

        self.stdout.write(self.style.SUCCESS(f"Products created with unit variations."))

# Total products with unit variations: 132
