# Generated by Django 5.0.9 on 2025-09-15 05:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_productionbatch_actual_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='batch_size',
            field=models.PositiveIntegerField(default=1, help_text='Standard batch size'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='production_time_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='version',
            field=models.CharField(blank=True, default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yield_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
