# Generated by Django 5.0.9 on 2025-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_restaurant_roles_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='branch_name',
            field=models.CharField(blank=True, help_text="Branch name for multi-location businesses (e.g., 'Debonairs Sandton')", max_length=200),
        ),
    ]
