# Generated by Django 5.0.9 on 2025-09-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_restaurantprofile_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='restaurant_roles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=20, null=True),
        ),
    ]
