# Generated by Django 5.0.9 on 2025-09-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_restaurantprofile_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='payment_terms',
            field=models.CharField(blank=True, default='Net 30', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='restaurant_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('admin', 'Admin'), ('staff', 'Staff')], default='restaurant', max_length=20),
        ),
    ]
