# Generated by Django 5.0.9 on 2025-09-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_restaurantprofile_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Special delivery requirements and notes from WhatsApp orders'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='order_pattern',
            field=models.CharField(blank=True, help_text="Typical order pattern (e.g., 'Tuesday orders - Italian restaurant supplies')", max_length=200),
        ),
    ]
