# Generated by Django 5.0.9 on 2025-09-15 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_restaurantprofile_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('private', 'Private Customer'), ('farm_manager', 'Farm Manager'), ('stock_taker', 'Stock Taker'), ('admin', 'Admin'), ('staff', 'Staff')], default='restaurant', max_length=20),
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, help_text='e.g., Operations, Inventory, Sales', max_length=100)),
                ('position', models.CharField(blank=True, help_text='e.g., Farm Manager, Stock Taker', max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp contact number', max_length=20)),
                ('access_level', models.CharField(choices=[('basic', 'Basic Access'), ('manager', 'Manager Access'), ('admin', 'Admin Access')], default='basic', max_length=20)),
                ('can_manage_inventory', models.BooleanField(default=False)),
                ('can_approve_orders', models.BooleanField(default=False)),
                ('can_manage_customers', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about role and responsibilities')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PrivateCustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('household', 'Household'), ('small_business', 'Small Business'), ('personal', 'Personal')], default='household', max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_instructions', models.TextField(blank=True)),
                ('preferred_delivery_day', models.CharField(choices=[('tuesday', 'Tuesday'), ('thursday', 'Thursday'), ('any', 'Any Day')], default='tuesday', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('order_notes', models.TextField(blank=True, help_text='Typical order patterns and preferences')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
    ]
