# Generated by Django 5.0.9 on 2025-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_user_type_farmprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='is_private_customer',
            field=models.BooleanField(default=False, help_text='Check if this is a private customer (individual) rather than a business'),
        ),
    ]
