# Generated by Django 5.0.9 on 2025-09-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_private_customer_field'),
        ('inventory', '0011_alter_productionrecipe_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='preferred_pricing_rule',
            field=models.ForeignKey(blank=True, help_text='Override automatic pricing rule selection with a specific rule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.pricingrule'),
        ),
    ]
