# Generated by Django 5.0.9 on 2025-09-06 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rawmaterialbatch_supplier'),
        ('suppliers', '0002_salesrep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialbatch',
            name='supplier_name',
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='supplier',
            field=models.ForeignKey(default=1, help_text='Supplier who provided this batch', on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier'),
            preserve_default=False,
        ),
    ]
