# Generated by Django 5.0.9 on 2025-09-06 13:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_rawmaterialbatch_supplier_name_and_more'),
        ('products', '0005_businesssettings_departmentkeyword'),
        ('suppliers', '0002_salesrep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_purchased', models.DecimalField(decimal_places=2, help_text='Quantity purchased at this price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('source_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('invoice', 'Invoice'), ('manual_entry', 'Manual Entry'), ('market_data', 'Market Data')], default='purchase_order', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Reference number (PO, Invoice, etc.)', max_length=100)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Economy'), ('R', 'Grade R - Reject/Processing')], default='B', max_length=10)),
                ('price_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when this price was effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Whether this price has been validated by a manager')),
                ('validation_notes', models.TextField(blank=True, help_text='Notes from price validation process')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.rawmaterial')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier who provided this price', null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                ('unit', models.ForeignKey(help_text='Unit of measure for this price', on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price History',
                'ordering': ['-price_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_average', models.DecimalField(blank=True, decimal_places=2, help_text='Average price over last 90 days', max_digits=10, null=True)),
                ('variance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage variance from historical average', max_digits=5, null=True)),
                ('validation_status', models.CharField(choices=[('within_range', 'Within Expected Range'), ('high_variance', 'High Variance - Review Required'), ('extreme_variance', 'Extreme Variance - Approval Required'), ('no_history', 'No Historical Data'), ('approved', 'Manually Approved'), ('rejected', 'Rejected')], default='within_range', max_length=20)),
                ('min_recent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_recent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('median_recent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('validation_notes', models.TextField(blank=True, help_text='Notes from validation process')),
                ('price_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='inventory.pricehistory')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Validation Result',
                'verbose_name_plural': 'Price Validation Results',
            },
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'price_date'], name='inventory_p_product_bc3f67_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['raw_material', 'price_date'], name='inventory_p_raw_mat_67ccb0_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['supplier', 'price_date'], name='inventory_p_supplie_269607_idx'),
        ),
    ]
