# Generated by Django 5.0.9 on 2025-09-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_pricehistory_pricevalidationresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedinventory',
            name='available_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finishedinventory',
            name='minimum_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finishedinventory',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finishedinventory',
            name='reserved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='quality_grade',
            field=models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Economy'), ('R', 'Grade R - Reject/Processing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='source_type',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('invoice', 'Invoice'), ('manual_entry', 'Manual Entry'), ('market_data', 'Market Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricevalidationresult',
            name='validation_status',
            field=models.CharField(choices=[('within_range', 'Within Expected Range'), ('high_variance', 'High Variance - Review Required'), ('extreme_variance', 'Extreme Variance - Approval Required'), ('no_history', 'No Historical Data'), ('approved', 'Manually Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='minimum_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
