# Generated by Django 5.0.9 on 2025-09-06 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_finishedinventory_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedinventory',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productionrecipe',
            name='processing_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionrecipe',
            name='version',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productionrecipe',
            name='yield_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='requires_batch_tracking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='quality_grade',
            field=models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Basic'), ('R', 'Rejected')], max_length=10),
        ),
    ]
