# Generated by Django 5.0.9 on 2025-09-06 15:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_finishedinventory_average_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='is_validated',
            field=models.BooleanField(blank=True, help_text='Whether this price has been validated by a manager', null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price_date',
            field=models.DateTimeField(blank=True, help_text='Date when this price was effective', null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='overhead_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='total_raw_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='waste_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productionrecipe',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionrecipe',
            name='output_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='is_acknowledged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='base_unit_multiplier',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='For conversion to base unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='is_weight',
            field=models.BooleanField(blank=True, help_text='True for weight-based, False for count-based', null=True),
        ),
    ]
