# Generated by Django 5.0.9 on 2025-09-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_pricingrule_customerpricelist_weeklypricereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='base_unit_multiplier',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='For conversion to base unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='is_weight',
            field=models.BooleanField(default=True, help_text='True for weight-based, False for count-based'),
        ),
    ]
