# Generated by Django 5.0.9 on 2025-10-08 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_productionrecipe_is_active_and_more'),
        ('products', '0016_alter_procurementbuffer_market_pack_unit_and_more'),
        ('suppliers', '0006_supplier_description_supplier_supplier_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('photo', models.ImageField(upload_to='invoices/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded - Awaiting Processing'), ('processing', 'Processing - OCR in Progress'), ('extracted', 'Data Extracted - Awaiting Weight Input'), ('completed', 'Completed - Ready for Stock Processing'), ('error', 'Error - Processing Failed')], default='uploaded', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the invoice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('supplier', 'invoice_date', 'original_filename')},
            },
        ),
        migrations.CreateModel(
            name='SupplierProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_product_code', models.CharField(blank=True, max_length=100)),
                ('supplier_product_description', models.CharField(max_length=255)),
                ('pricing_strategy', models.CharField(choices=[('per_kg', 'Price per kg (loose/bulk)'), ('per_package', 'Price per package (as delivered)'), ('per_unit', 'Price per unit (each, bunch, head)'), ('custom', 'Custom pricing calculation')], max_length=20)),
                ('package_size_kg', models.DecimalField(blank=True, decimal_places=2, help_text="If per_package, what's the package size in kg?", max_digits=10, null=True)),
                ('units_per_package', models.PositiveIntegerField(blank=True, help_text='If per_unit, how many units per package?', null=True)),
                ('notes', models.TextField(blank=True, help_text="Karl's notes about this mapping")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('our_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'ordering': ['supplier', 'supplier_product_description'],
                'unique_together': {('supplier', 'supplier_product_code', 'supplier_product_description')},
            },
        ),
        migrations.CreateModel(
            name='ExtractedInvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(help_text='Line number on invoice')),
                ('product_code', models.CharField(blank=True, help_text='Supplier product code', max_length=100)),
                ('product_description', models.CharField(help_text='Product description from invoice', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity from invoice', max_digits=10)),
                ('unit', models.CharField(help_text='Unit from invoice (bag, box, kg, etc)', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line', max_digits=10)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Actual weight in kg (handwritten on invoice)', max_digits=10, null=True)),
                ('needs_weight_input', models.BooleanField(default=True)),
                ('needs_product_matching', models.BooleanField(default=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_items', to='inventory.invoicephoto')),
                ('supplier_mapping', models.ForeignKey(blank=True, help_text="Karl's mapping decision for this supplier product", null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplierproductmapping')),
            ],
            options={
                'ordering': ['invoice_photo', 'line_number'],
            },
        ),
    ]
