# Generated by Django 5.0.9 on 2025-10-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_invoicephoto_supplierproductmapping_and_more'),
    ]

    operations = [
    ]
