# Generated by Django 5.0.9 on 2025-11-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_invoice_product_matching_fields'),
        ('inventory', '0013_auto_20251009_1002'),
    ]

    operations = [
    ]
