# Generated by Django 5.0.9 on 2025-11-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_merge_20251103_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedinvoicedata',
            name='calculated_cost_per_kg',
        ),
        migrations.RemoveField(
            model_name='extractedinvoicedata',
            name='discrepancy_notes',
        ),
        migrations.RemoveField(
            model_name='extractedinvoicedata',
            name='has_discrepancy',
        ),
        migrations.RemoveField(
            model_name='extractedinvoicedata',
            name='matched_product',
        ),
        migrations.RemoveField(
            model_name='extractedinvoicedata',
            name='po_item',
        ),
        migrations.RemoveField(
            model_name='extractedinvoicedata',
            name='pricing_strategy',
        ),
        migrations.RemoveField(
            model_name='extractedinvoicedata',
            name='quantity_variance',
        ),
        migrations.RemoveField(
            model_name='invoicephoto',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='invoicephoto',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='supplierproductmapping',
            name='average_weight_kg',
        ),
        migrations.RemoveField(
            model_name='supplierproductmapping',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='supplierproductmapping',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='supplierproductmapping',
            name='times_used',
        ),
    ]
