# Generated by Django 5.0.9 on 2025-11-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_extractedinvoicedata_calculated_cost_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (for stock take entries)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('raw_receive', 'Raw Material Received'), ('raw_adjust', 'Raw Material Adjustment'), ('raw_consume', 'Raw Material Consumed in Production'), ('raw_waste', 'Raw Material Waste/Spoilage'), ('production', 'Production Output'), ('production_waste', 'Production Waste'), ('finished_adjust', 'Finished Inventory Adjustment (Add)'), ('finished_set', 'Finished Inventory Set (Replace)'), ('finished_reserve', 'Stock Reserved for Order'), ('finished_release', 'Stock Released (Order Cancelled)'), ('finished_sell', 'Stock Sold (Order Delivered)'), ('finished_waste', 'Finished Product Waste')], max_length=20),
        ),
    ]
