# Generated by Django 5.0.9 on 2025-09-12 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_parsed_by_ai_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('chat_name', models.CharField(max_length=200)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('content', models.TextField()),
                ('cleaned_content', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('order', 'Customer Order'), ('stock', 'Stock Update'), ('instruction', 'Instruction/Note'), ('demarcation', 'Order Day Demarcation'), ('other', 'Other')], default='other', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processed', models.BooleanField(default=False)),
                ('parsed_items', models.JSONField(default=list)),
                ('instructions', models.TextField(blank=True)),
                ('edited', models.BooleanField(default=False)),
                ('original_content', models.TextField(blank=True)),
                ('order_day', models.CharField(blank=True, max_length=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('order_day', models.CharField(max_length=10)),
                ('items', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_to_orders', models.ManyToManyField(blank=True, to='orders.order')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappmessage')),
            ],
            options={
                'ordering': ['-stock_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDayDemarcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_day', models.CharField(max_length=10)),
                ('demarcation_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('orders_collected', models.ManyToManyField(blank=True, to='orders.order')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappmessage')),
            ],
            options={
                'ordering': ['-demarcation_date'],
            },
        ),
        migrations.CreateModel(
            name='MessageProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('classified', 'Message Classified'), ('parsed', 'Items Parsed'), ('order_created', 'Order Created'), ('stock_updated', 'Stock Updated'), ('edited', 'Message Edited'), ('error', 'Processing Error')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='whatsapp.whatsappmessage')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['message_type', 'processed'], name='whatsapp_wh_message_e4ca13_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['timestamp'], name='whatsapp_wh_timesta_795c73_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['sender_phone'], name='whatsapp_wh_sender__0884a5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockupdate',
            index=models.Index(fields=['order_day', 'processed'], name='whatsapp_st_order_d_e21d42_idx'),
        ),
        migrations.AddIndex(
            model_name='stockupdate',
            index=models.Index(fields=['stock_date'], name='whatsapp_st_stock_d_f31ae8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdaydemarcation',
            unique_together={('order_day', 'demarcation_date')},
        ),
    ]
