# Generated by Django 5.0.9 on 2025-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='forwarded_info',
            field=models.TextField(blank=True, help_text='Info about forwarded message source'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_info',
            field=models.TextField(blank=True, help_text='Additional media info like voice duration, file size, etc.'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_type',
            field=models.CharField(blank=True, help_text='Type of media: image, voice, video, document, sticker', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL for image/video/document', null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='reply_content',
            field=models.TextField(blank=True, help_text='Content of message being replied to'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('order', 'Customer Order'), ('stock', 'Stock Update'), ('instruction', 'Instruction/Note'), ('demarcation', 'Order Day Demarcation'), ('image', 'Image Message'), ('voice', 'Voice Message'), ('video', 'Video Message'), ('document', 'Document Message'), ('sticker', 'Sticker Message'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
