# Generated by Django 5.0.9 on 2025-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_parsed_by_ai_alter_order_status_and_more'),
        ('whatsapp', '0002_whatsappmessage_forwarded_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['is_deleted'], name='whatsapp_wh_is_dele_36701d_idx'),
        ),
    ]
