# Generated by Django 5.0.9 on 2025-09-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsappmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='manual_company',
            field=models.CharField(blank=True, help_text='Manually selected company name', max_length=200, null=True),
        ),
    ]
