# Generated by Django 5.0.9 on 2025-09-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_whatsappmessage_manual_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='expansion_failed',
            field=models.BooleanField(default=False, help_text='Whether expansion was attempted but failed'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='needs_manual_review',
            field=models.BooleanField(default=False, help_text='Flagged for manual review'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='original_preview',
            field=models.TextField(blank=True, help_text='Preview text before expansion'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='raw_html',
            field=models.TextField(blank=True, help_text='Raw HTML from WhatsApp message element'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='review_reason',
            field=models.CharField(blank=True, help_text='Reason for manual review', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='was_expanded',
            field=models.BooleanField(default=False, help_text='Whether message was expanded from truncated state'),
        ),
    ]
