# Generated by Django 5.0.9 on 2025-09-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_whatsappmessage_expansion_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='content_hash',
            field=models.CharField(blank=True, help_text='MD5 hash of content for deduplication', max_length=32),
        ),
    ]
