# Generated by Django 5.0.9 on 2025-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_add_content_hash_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='processing_notes',
            field=models.TextField(blank=True, help_text='Processing status, errors, and results'),
        ),
    ]
