# Generated by Django 5.0.9 on 2025-09-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_expand_action_column'),
        ('whatsapp', '0008_expand_action_column'),
    ]

    operations = [
    ]
