# Generated by Django 5.0.9 on 2025-10-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_merge_20250929_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
