# Generated by Django 5.0.9 on 2025-09-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_purchaseorder_order_and_more'),
        ('suppliers', '0002_salesrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='suppliers.salesrep'),
        ),
    ]
