# Generated by Django 5.0.9 on 2025-08-30 13:41

import django.core.validators
import django.db.models.deletion
import orders.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_common_names_product_in_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received via WhatsApp'), ('parsed', 'AI Parsed'), ('confirmed', 'Manager Confirmed'), ('po_sent', 'PO Sent to Sales Rep'), ('po_confirmed', 'Sales Rep Confirmed'), ('delivered', 'Delivered to Customer'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('order_date', models.DateField(validators=[orders.models.validate_order_date])),
                ('delivery_date', models.DateField(validators=[orders.models.validate_delivery_date])),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('original_message', models.TextField(blank=True)),
                ('parsed_by_ai', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_text', models.CharField(blank=True, max_length=200)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('manually_corrected', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
