# Generated by Django 5.0.9 on 2025-09-15 05:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_parsed_by_ai_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parsed_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received via WhatsApp'), ('parsed', 'AI Parsed'), ('confirmed', 'Manager Confirmed'), ('po_sent', 'PO Sent to Sales Rep'), ('po_confirmed', 'Sales Rep Confirmed'), ('delivered', 'Delivered to Customer'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='manually_corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(default='piece', max_length=20),
        ),
    ]
