# Generated by Django 5.0.9 on 2025-10-07 11:28

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_parsed_by_ai_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=orders.models.get_order_status_choices, default='received', max_length=20),
        ),
    ]
