# Generated by Django 5.0.9 on 2025-11-12 12:00

from decimal import Decimal
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
        ('products', '0007_alter_product_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='source_product',
            field=models.ForeignKey(
                blank=True,
                help_text='Product from which stock will be deducted (if different from the ordered product)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='source_order_items',
                to='products.product'
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='source_quantity',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Quantity to deduct from source product (e.g., kg from bulk product)',
                max_digits=8,
                null=True,
                validators=[MinValueValidator(Decimal('0.01'))]
            ),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_items',
                to='products.product'
            ),
        ),
    ]

