# Generated by Django 4.2.7 on 2025-07-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_businesshours_companyinfo_faq_pagecontent_teammember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(default='#16a34a', help_text='Hex color code (e.g. #16a34a)', max_length=7),
        ),
    ]
