# Generated by Django 5.0.9 on 2025-08-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_department_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='common_names',
            field=models.JSONField(blank=True, default=list, help_text='Alternative names for AI parsing: ["onions", "red onions", "onion"]'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_level',
            field=models.CharField(choices=[('high', 'High Stock'), ('medium', 'Medium Stock'), ('low', 'Low Stock'), ('out', 'Out of Stock')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='typical_order_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Typical restaurant order quantity', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', max_length=50),
        ),
    ]
