# Generated by Django 5.0.9 on 2025-09-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_businesssettings_departmentkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='is_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code (e.g. #16a34a)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='common_names',
            field=models.JSONField(blank=True, help_text='Alternative names for AI parsing: ["onions", "red onions", "onion"]', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_level',
            field=models.CharField(choices=[('high', 'High Stock'), ('medium', 'Medium Stock'), ('low', 'Low Stock'), ('out', 'Out of Stock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='typical_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typical restaurant order quantity', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='Simplified: kg, bunch, piece', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
