# Generated by Django 5.0.9 on 2025-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_businesshours_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_level',
            field=models.CharField(blank=True, choices=[('high', 'High Stock'), ('medium', 'Medium Stock'), ('low', 'Low Stock'), ('out', 'Out of Stock')], max_length=20, null=True),
        ),
    ]
