# Generated by Django 5.0.9 on 2025-09-14 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_unique_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('needs_setup', 'Needs Setup'), ('low_stock', 'Low Stock'), ('no_price', 'No Price Set'), ('missing_recipe', 'Missing Recipe')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_by_order', models.CharField(blank=True, help_text='Order number that triggered this alert', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.JSONField(default=list, help_text='List of ingredient items with quantities')),
                ('instructions', models.TextField(blank=True)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('yield_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('yield_unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('piece', 'Piece'), ('box', 'Box'), ('punnet', 'Punnet'), ('bag', 'Bag'), ('bunch', 'Bunch'), ('head', 'Head')], default='piece', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.DeleteModel(
            name='BusinessHours',
        ),
        migrations.RemoveField(
            model_name='businesssettings',
            name='default_count_unit',
        ),
        migrations.RemoveField(
            model_name='businesssettings',
            name='default_department',
        ),
        migrations.RemoveField(
            model_name='businesssettings',
            name='default_supplier',
        ),
        migrations.RemoveField(
            model_name='businesssettings',
            name='default_weight_unit',
        ),
        migrations.RemoveField(
            model_name='businesssettings',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.AlterUniqueTogether(
            name='departmentkeyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='departmentkeyword',
            name='department',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['department__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='department',
            name='color',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'department')},
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='needs_setup',
            field=models.BooleanField(default=False, help_text='Product was auto-created and needs pricing/inventory setup'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('piece', 'Piece'), ('box', 'Box'), ('punnet', 'Punnet'), ('bag', 'Bag'), ('bunch', 'Bunch'), ('head', 'Head')], default='piece', max_length=20),
        ),
        migrations.AddField(
            model_name='productalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.product'),
        ),
        migrations.AddField(
            model_name='productalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipe', to='products.product'),
        ),
        migrations.DeleteModel(
            name='BusinessSettings',
        ),
        migrations.DeleteModel(
            name='DepartmentKeyword',
        ),
        migrations.RemoveField(
            model_name='product',
            name='common_names',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='typical_order_quantity',
        ),
    ]
