# Generated by Django 5.0.9 on 2025-09-15 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_businesssettings_departmentkeyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProcurementRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('for_date', models.DateField(help_text='Market trip date')),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved by Karl'), ('purchased', 'Purchased at Market'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('analysis_data', models.JSONField(default=dict, help_text='Detailed analysis: orders, stock levels, predictions')),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reasoning', models.TextField(help_text='Why this quantity is recommended')),
                ('priority', models.CharField(choices=[('critical', 'Critical - Out of Stock'), ('high', 'High - Low Stock'), ('medium', 'Medium - Upcoming Orders'), ('low', 'Low - Buffer Stock')], default='medium', max_length=20)),
                ('source_orders', models.JSONField(default=list, help_text='Order IDs that drove this recommendation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.marketprocurementrecommendation')),
            ],
            options={
                'ordering': ['priority', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoilage_rate', models.DecimalField(decimal_places=3, default=0.15, help_text='Expected spoilage rate (0.15 = 15%)', max_digits=5)),
                ('cutting_waste_rate', models.DecimalField(decimal_places=3, default=0.1, help_text='Waste from cutting/trimming (0.10 = 10%)', max_digits=5)),
                ('quality_rejection_rate', models.DecimalField(decimal_places=3, default=0.05, help_text='Rate of quality rejections (0.05 = 5%)', max_digits=5)),
                ('total_buffer_rate', models.DecimalField(decimal_places=3, default=0.3, help_text='Total buffer rate (auto-calculated)', max_digits=5)),
                ('market_pack_size', models.DecimalField(decimal_places=2, default=1, help_text='Standard market pack size (e.g., 10kg boxes)', max_digits=10)),
                ('market_pack_unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('piece', 'Piece'), ('box', 'Box'), ('punnet', 'Punnet'), ('bag', 'Bag'), ('bunch', 'Bunch'), ('head', 'Head')], default='kg', max_length=20)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('peak_season_months', models.JSONField(default=list, help_text='List of peak season months [1-12]')),
                ('peak_season_buffer_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Extra buffer during peak season', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_buffer', to='products.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
    ]
