# Generated by Django 5.0.9 on 2025-09-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_marketprocurementrecommendation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'department', 'unit')},
        ),
    ]
