# Generated by Django 5.0.9 on 2025-09-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_unique_together'),
        ('suppliers', '0006_supplier_description_supplier_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketprocurementitem',
            name='is_fambri_available',
            field=models.BooleanField(default=False, help_text='Whether Fambri Internal can supply this item'),
        ),
        migrations.AddField(
            model_name='marketprocurementitem',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, help_text='Recommended supplier based on Fambri-first logic', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='marketprocurementitem',
            name='procurement_method',
            field=models.CharField(choices=[('market', 'Market Purchase'), ('supplier', 'Direct Supplier'), ('fambri', 'Fambri Internal'), ('mixed', 'Multi-Supplier Split')], default='market', help_text='Recommended procurement method', max_length=20),
        ),
        migrations.AddField(
            model_name='marketprocurementitem',
            name='supplier_lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Lead time from supplier', null=True),
        ),
        migrations.AddField(
            model_name='marketprocurementitem',
            name='supplier_product',
            field=models.ForeignKey(blank=True, help_text='Specific supplier product with pricing and availability', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplierproduct'),
        ),
        migrations.AddField(
            model_name='marketprocurementitem',
            name='supplier_quality_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quality rating from supplier performance tracking', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='marketprocurementitem',
            name='supplier_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual supplier price if available', max_digits=10, null=True),
        ),
    ]
