# Generated by Django 5.0.9 on 2025-09-28 23:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_integrate_supplier_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='auto_create_buffers',
            field=models.BooleanField(default=True, help_text='Automatically create procurement buffers for new products'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='buffer_calculation_method',
            field=models.CharField(choices=[('additive', 'Additive (sum all rates)'), ('multiplicative', 'Multiplicative (compound rates)')], default='additive', help_text='Method for calculating total buffer rates', max_length=20),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='default_cutting_waste_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.10'), help_text='Default cutting waste rate for new products (0.10 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='default_market_pack_size',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.0'), help_text='Default market pack size for new products', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='default_peak_season_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.3'), help_text='Default peak season buffer multiplier', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))]),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='default_quality_rejection_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.05'), help_text='Default quality rejection rate for new products (0.05 = 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='default_spoilage_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.15'), help_text='Default spoilage rate for new products (0.15 = 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='department_buffer_settings',
            field=models.JSONField(default=dict, help_text='Department-specific buffer settings as JSON'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='enable_seasonal_adjustments',
            field=models.BooleanField(default=True, help_text='Enable seasonal buffer adjustments'),
        ),
        migrations.AlterField(
            model_name='procurementbuffer',
            name='market_pack_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('piece', 'Piece'), ('each', 'Each'), ('head', 'Head'), ('bunch', 'Bunch'), ('box', 'Box'), ('bag', 'Bag'), ('punnet', 'Punnet'), ('packet', 'Packet'), ('crate', 'Crate'), ('tray', 'Tray'), ('bundle', 'Bundle'), ('L', 'Liter'), ('ml', 'Milliliter')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('piece', 'Piece'), ('each', 'Each'), ('head', 'Head'), ('bunch', 'Bunch'), ('box', 'Box'), ('bag', 'Bag'), ('punnet', 'Punnet'), ('packet', 'Packet'), ('crate', 'Crate'), ('tray', 'Tray'), ('bundle', 'Bundle'), ('L', 'Liter'), ('ml', 'Milliliter')], default='piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yield_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('piece', 'Piece'), ('each', 'Each'), ('head', 'Head'), ('bunch', 'Bunch'), ('box', 'Box'), ('bag', 'Bag'), ('punnet', 'Punnet'), ('packet', 'Packet'), ('crate', 'Crate'), ('tray', 'Tray'), ('bundle', 'Bundle'), ('L', 'Liter'), ('ml', 'Milliliter')], default='piece', max_length=20),
        ),
    ]
