# Generated by Django 5.0.9 on 2025-10-07 11:28

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_businesssettings_auto_create_buffers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementbuffer',
            name='market_pack_unit',
            field=models.CharField(choices=products.models.get_unit_choices, default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=products.models.get_unit_choices, default='piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yield_unit',
            field=models.CharField(choices=products.models.get_unit_choices, default='piece', max_length=20),
        ),
    ]
