# Generated by Django 5.0.9 on 2025-10-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_procurementbuffer_market_pack_unit_and_more'),
        ('suppliers', '0006_supplier_description_supplier_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='procurement_supplier',
            field=models.ForeignKey(blank=True, help_text='Primary supplier for market procurement. NULL = use Fambri garden/no procurement needed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procured_products', to='suppliers.supplier'),
        ),
    ]
