# Generated by Django 5.0.9 on 2025-10-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_procurement_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='enable_buffer_calculations',
            field=models.BooleanField(default=True, help_text='Enable/disable all buffer calculations globally'),
        ),
    ]
