# Generated by Django 5.0.9 on 2025-11-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_supplier_cost_fields'),
        ('products', '0021_product_supplier_cost_fields'),
    ]

    operations = [
    ]
