# Generated by Django 5.0.9 on 2025-11-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_merge_20251103_1126'),
        ('products', '0099_product_unlimited_stock'),
    ]

    operations = [
    ]
