# Generated by Django 5.0.9 on 2025-11-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_profile_timestamps'),
        ('products', '0100_merge_20251116_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPackageRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_package_sizes', models.JSONField(default=list, help_text='List of allowed package sizes in grams (e.g., [100, 150]). Empty list means all sizes allowed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_restrictions', to='products.department')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_restrictions', to='accounts.restaurantprofile')),
            ],
            options={
                'verbose_name': 'Restaurant Package Restriction',
                'verbose_name_plural': 'Restaurant Package Restrictions',
                'ordering': ['restaurant__business_name', 'department__name'],
                'unique_together': {('restaurant', 'department')},
            },
        ),
    ]
